data:
  data_path: data/Visadataset.csv


model:
  model_path: model/LightGBM.pkl

encoder:
  encoder_path: model/encoder.pkl
  categorical_cols: ['continent', 'education_of_employee', 'has_job_experience', 'requires_job_training', 'region_of_employment', 'unit_of_wage', 'full_time_position'] 
model_params:
  n_estimators: 170
  max_depth: 10
  learning_rate: 0.0002
